#!/usr/bin/env bash
# Running the infinite loop script in the background
./infinity_beyond.sh &

# Locating the PID of the '4-to_infinity_and_beyond' process
pid=$(pgrep -f "4-to_infinity_and_beyond")

# Showing the PID
echo "PID of 4-to_infinity_and_beyond process: $pid"

# Stopping the process using the kill command
kill "$pid"
