#!/usr/bin/env bash
# Func to deal with the termination signal
function handle_termination() {
    echo "Termination signal received. Stopping '4-to_infinity_and_beyond' process."
    exit 0
}

# Register the signal handler
trap handle_termination SIGINT

# Infinite loop
while true; do
    echo "To infinity and beyond"
    sleep 2
done
